name: dartedflib
description: EDF lib for Dart (FFI bindings to edflib, a C-library created by Teuniz.net)
version: 0.1.0

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  dylib: ^0.3.2
  ffi: ^2.0.1
  version: ^3.0.2

dev_dependencies:
  ffigen: ^6.1.1
  lints: ^2.0.1
  test: ^1.21.4
  dart_code_metrics: ^4.19.2
  dependency_validator: ^3.2.2
  path: ^1.8.3
  random_string: ^2.3.1
  intl: ^0.18.0
